import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";
import { ThemeProvider } from "@/components/theme-provider";
// import { Providers } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // not replaced : <html lang="en" > <body>
      
    <html lang="en" className='light'>
      <body className={`${inter.className}, flex flex-col `}>
        {/* <Providers> */}
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Header/>
        {children}
        <Footer/>
        </ThemeProvider>
        {/* </Providers> */}
        </body>
    </html>
  );
}
